### DISCUSSION TITLE
Cadence cluster networking configuration

### DISCUSSION THREAD

**Discussion by longquanzheng** [uber/cadence#4356] [General]
_**NOTE: Please leave your questions below and we can improve on this topic**_

Here uses configuration in [0.21.0](https://pkg.go.dev/github.com/uber/cadence@v0.21.0/common/config#Config) as example. But the other versions should be the same. 

### Ringpop configuration 
[Ringpop](https://pkg.go.dev/github.com/uber/cadence@v0.21.0/common/config#Ringpop) is to connect all the nodes within the same cluster. 
  * Usually **bootstrapMode** should be DNS, see [example](https://github.com/banzaicloud/banzai-charts/blob/d8d883e026bf1b492b1aeb89383eab8105e5ab2b/cadence/templates/server-configmap.yaml#L69). Using DNS is recommended because if any of the IP addresses of bootstrap is not up, hosts can't join the cluster. This could be a problem for IP changes or restarting or scaling up. 
  * bootstrapHosts can be DNS of any service, or even all of them like the example. 
  * If you use IP mode, make sure that the host with the IP is always up. 
  * Ringpop requires all bootstrap IPs to be up during startup(within **maxJoinDuration**) This could be a chicken-egg problem. To break this circle the IPs needs to be published even the nodes are not ready. In Kubernetes, this is achieved by [publishNotReadyAddresses](https://github.com/banzaicloud/banzai-charts/blob/d8d883e026bf1b492b1aeb89383eab8105e5ab2b/cadence/templates/server-service.yaml#L53) 
  * We probably can [remove the restriction](https://github.com/uber/cadence/issues/4359) in the future, but that could have some risk of network partition issue. 

To verify the DNS, you should be able to use `nslookup` command to see all the IPs behind it. 

### publicClient configuration 
It's for server worker service to connect to frontend. 
* **HostPort** should be the DNS address of the frontend service. 
To verify the DNS, you should be able to use `nslookup` command to see all the IPs behind it. 
* If using Kubernetes, [ClusterIP should work as a DN](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/)S, see helmchart [values](https://github.com/banzaicloud/banzai-charts/blob/d8d883e026bf1b492b1aeb89383eab8105e5ab2b/cadence/values.yaml#L129) and [template](https://github.com/banzaicloud/banzai-charts/blob/d8d883e026bf1b492b1aeb89383eab8105e5ab2b/cadence/templates/server-service.yaml#L14)
See related [discussion](https://github.com/banzaicloud/banzai-charts/pull/1278#discussion_r681268140)
* Alternatively, you can use [LoadBalancer](https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer). This would allow your client workers to access frontend service from outside of K8s. 

### `clusterMetadata.clusterInformation.<currentClusterName>.rpcAddress` configuration 
* It must be exactly the same as publicClient.hostPort
* This is duplicated, and will be improved in https://github.com/uber/cadence/issues/3984

### Service.RPC configuration
[service.rpc ](https://pkg.go.dev/github.com/uber/cadence@v0.21.0/common/config#RPC) is to configure the service to listen on certain IP and port. 

* Only bindOnIP should be used in a cluster. bindOnLocalHost is only for local testing server
* The IP address will be used for not only accepting requests, but also discovery address in Ringpop. See[ how Ringpop does the node discovery.](https://stackoverflow.com/questions/68417033/how-frontend-service-know-the-change-of-history-services-in-cadence/68418069#68418069) 
* Therefore, the IP needs to be the IP of the instance. [In K8s setup, it's a PodID](https://github.com/banzaicloud/banzai-charts/blob/d8d883e026bf1b492b1aeb89383eab8105e5ab2b/cadence/templates/server-configmap.yaml#L87). 

## Multiple Server clusters with XDC(global domain) replication group
[XDC(global domain) is a replication group of multiple cadence clusters](https://cadenceworkflow.io/docs/concepts/cross-dc-replication/). 
Based on the "Single server cluster without replication", **clusterMetadata** needs to be updated to configure multiple clusters to connect to each other.  

Supposed we have two clusters, **clusterA** and **clusterB**

Config of clusterA should be:
```
clusterMetadata:
  enableGlobalDomain: true
  failoverVersionIncrement: 10
  masterClusterName: "clusterA" 
  currentClusterName: "clusterA"
  clusterInformation:
    clusterA:
      enabled: true
      initialFailoverVersion: 1
      rpcName: "cadence-frontend"
      rpcAddress: "<frontend DNS of clusterA>:7933"
    clusterB:
      enabled: true
      initialFailoverVersion: 0
      rpcName: "cadence-frontend"
      rpcAddress: "<frontend DNS of clusterB>:7933"
```

Config of clusterB should be:
```
clusterMetadata:
  enableGlobalDomain: true
  failoverVersionIncrement: 10
  masterClusterName: "clusterA" 
  currentClusterName: "clusterB"
  clusterInformation:
    clusterA:
      enabled: true
      initialFailoverVersion: 1
      rpcName: "cadence-frontend"
      rpcAddress: "<frontend DNS of clusterA>:7933"
    clusterB:
      enabled: true
      initialFailoverVersion: 0
      rpcName: "cadence-frontend"
      rpcAddress: "<frontend DNS of clusterB>:7933"
```

Some rules of the config:
* **currentClusterName** must the different for each cluster. This means which this deployment IS. 
* **masterClusterName** should be the same in both cluster. This decides which cluster can register new domains and update domain information. 
* Failover can be made from any cluster. It's NOT decided by masterClusterName
* **failoverVersionIncrement** decides the maximum number clusters in this replication groups 
* **initialFailoverVersion** is the identifier of each cluster. 0<= the value < failoverVersionIncrement
* the value of **initialFailoverVersion** and **failoverVersionIncrement** should be exactly the same across all clusters. 
* rpcAddress is for two clusters talking to each other. If the clusters are in a different Kubernetes clusters, you may have to use LoadBalancer because ClusterIP will not work across two K8s. 

## Client worker 
Client worker is the worker that is running your workflow and activity code. 
* Recommended to use DNS to connect to frontend service 

## Related discussions 
https://github.com/uber/cadence/issues/4143
https://github.com/uber/cadence/issues/3150
https://github.com/uber/cadence/issues/3054

https://github.com/banzaicloud/banzai-charts/pull/1278

**Comment by ceearrashee** [comment]
Hello to continue of discussion:
You ask me about domain lookup:
```bash
/paser-staging-cadence-frontend/~$: nslookup paser-staging-cadence-frontend
Server:         10.152.183.10
Address:        10.152.183.10:53

** server can't find paser-staging-cadence-frontend.cluster.local: NXDOMAIN

** server can't find paser-staging-cadence-frontend.svc.cluster.local: NXDOMAIN

** server can't find paser-staging-cadence-frontend.cluster.local: NXDOMAIN

*** Can't find paser-staging-cadence-frontend.paser-staging.svc.cluster.local: No answer

** server can't find paser-staging-cadence-frontend.svc.cluster.local: NXDOMAIN

Name:   paser-staging-cadence-frontend.paser-staging.svc.cluster.local
Address: 10.152.183.33
```

Domain name resolved properly because domain description works.
```bash
/paser-staging-cadence-frontend/~$: cadence d desc
Name: paser
UUID: dcc71fdb-44eb-41f7-940d-96df1c1e59d3
Description: 
OwnerEmail: 
DomainData: map[]
Status: REGISTERED
RetentionInDays: 365
EmitMetrics: false
ActiveClusterName: active
Clusters: active
HistoryArchivalStatus: DISABLED
VisibilityArchivalStatus: DISABLED
Bad binaries to reset:
+-----------------+----------+------------+--------+
| BINARY CHECKSUM | OPERATOR | START TIME | REASON |
+-----------------+----------+------------+--------+
+-----------------+----------+------------+--------+
```

Other services also work properly. A problem occurs only while I try to update the domain (in other cases, not tested). At the beginning (around two years ago), we created a cluster with retention days 365, but now the database is too big, and our team decided to decrease retention days to 30 as a maximal value for new clusters.

**Reply by longquanzheng** [reply]
What is the error you run into when update the retention? 

Do you use helm chart and updated recently? There is a bug and they just released a bug fix. https://github.com/banzaicloud/banzai-charts/issues/1275#issuecomment-891208351

Basically the chart changed the cluster name while the domain still use the older names.

**Reply by ceearrashee** [reply]
Hello! I started the problem discussed in the slack thread: https://uber-cadence.slack.com/archives/CL22WDF70/p1627974339017100

Yes, I used the latest chart, `0.20.3`, but an error is still present. Actual `docker.yaml` after cluster update:

```yaml
log:
  stdout: true
  level: "debug,info"
  levelKey: "level"

persistence:
  defaultStore: default
  visibilityStore: visibility
  numHistoryShards: 512
  datastores:
    default:
      sql:
        pluginName: mysql
        databaseName: cadence
        connectAddr: "paser-staging-cadence-mysql.paser-staging.svc.cluster.local:3306"
        connectProtocol: "tcp"
        user: cadence
        password: cadence
    visibility:
      sql:
        pluginName: mysql
        databaseName: cadence_visibility
        connectAddr: "paser-staging-cadence-mysql.paser-staging.svc.cluster.local:3306"
        connectProtocol: "tcp"
        user: cadence
        password: cadence

ringpop:
  name: cadence
  bootstrapMode: dns
  bootstrapHosts:
    - paser-staging-cadence-frontend-headless:7833
    - paser-staging-cadence-frontend-headless:7933
    - paser-staging-cadence-history-headless:7834
    - paser-staging-cadence-history-headless:7934
    - paser-staging-cadence-matching-headless:7835
    - paser-staging-cadence-matching-headless:7935
    - paser-staging-cadence-worker-headless:7939
  maxJoinDuration: 30s

services:
  frontend:
    rpc:
      grpcPort: 7833
      port: 7933
      bindOnIP: 10.1.207.112
    metrics:
      tags:
        type: frontend
      prometheus:
        timerType: histogram
        listenAddress: "0.0.0.0:9090"

  history:
    rpc:
      grpcPort: 7834
      port: 7934
      bindOnIP: 10.1.207.112
    metrics:
      tags:
        type: history
      prometheus:
        timerType: histogram
        listenAddress: "0.0.0.0:9090"

  matching:
    rpc:
      grpcPort: 7835
      port: 7935
      bindOnIP: 10.1.207.112
    metrics:
      tags:
        type: matching
      prometheus:
        timerType: histogram
        listenAddress: "0.0.0.0:9090"

  worker:
    rpc:
      port: 7939
      bindOnIP: 10.1.207.112
    metrics:
      tags:
        type: worker
      prometheus:
        timerType: histogram
        listenAddress: "0.0.0.0:9090"

clusterMetadata:
  enableGlobalDomain: false
  failoverVersionIncrement: 10
  masterClusterName: "primary"
  currentClusterName: "primary"
  clusterInformation:
    primary:
      enabled: true
      initialFailoverVersion: 0
      rpcName: "cadence-frontend"
      rpcAddress: cadence:7933

dcRedirectionPolicy:
  policy: selected-apis-forwarding
  toDC: ""

archival:
  status: "disabled"

publicClient:
  hostPort: "paser-staging-cadence-frontend:7933"

dynamicConfigClient:
  filepath: "/etc/cadence/config/dynamicconfig/config.yaml"
  pollInterval: "10s"
```


An error occurred while I tried to update retention days:
```bash
/etc/cadence $ cadence --do paser --address paser-staging-cadence-frontend:7933 
d up --rd 30
Error: Operation UpdateDomain failed.
Error Details: BadRequestError{Message: Invalid cluster name: active}
Stack trace:
goroutine 1 [running]:
runtime/debug.Stack(0xd, 0x0, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/uber/cadence/tools/cli.printError(0x2502edd, 0x1e, 0x2a61660, 0xc000312330)
        /cadence/tools/cli/util.go:536 +0x2ad
github.com/uber/cadence/tools/cli.ErrorAndExit(0x2502edd, 0x1e, 0x2a61660, 0xc000312330)
        /cadence/tools/cli/util.go:547 +0x49
github.com/uber/cadence/tools/cli.(*domainCLIImpl).UpdateDomain(0xc00030ce80, 0xc000102840)
        /cadence/tools/cli/domainCommands.go:276 +0x457
github.com/uber/cadence/tools/cli.newDomainCommands.func2(0xc000102840)
        /cadence/tools/cli/domain.go:82 +0x48
github.com/urfave/cli.HandleAction(0x203b6e0, 0x25ac418, 0xc000102840, 0xc000102840, 0x0)
        /go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:528 +0x127
github.com/urfave/cli.Command.Run(0x24d0694, 0x6, 0x0, 0x0, 0xc000433080, 0x2, 0x2, 0x2505f3c, 0x1f, 0x0, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:174 +0x528
github.com/urfave/cli.(*App).RunAsSubcommand(0xc00036f500, 0xc000102160, 0x0, 0x0)
        /go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:407 +0x882
github.com/urfave/cli.Command.startApp(0x24cfb54, 0x6, 0x0, 0x0, 0xc000107ac0, 0x1, 0x1, 0x24ee32c, 0x16, 0x0, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:373 +0x845
github.com/urfave/cli.Command.Run(0x24cfb54, 0x6, 0x0, 0x0, 0xc000107ac0, 0x1, 0x1, 0x24ee32c, 0x16, 0x0, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:102 +0x9d6
github.com/urfave/cli.(*App).Run(0xc00036f340, 0xc00003a090, 0x9, 0x9, 0x0, 0x0)
        /go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:279 +0x731
main.main()
        /cadence/cmd/tools/cli/main.go:37 +0x4f
```

**Reply by longquanzheng** [reply]
The clusterMeta section needs to be 
```
clusterMetadata:
  enableGlobalDomain: true
  failoverVersionIncrement: 10
  masterClusterName: "active"
  currentClusterName: "active"
  clusterInformation:
    active:
      enabled: true
      initialFailoverVersion: 0
      rpcName: "cadence-frontend"
      rpcAddress: cadence:7933
```

so that you can continue to update the domain

I’m not very sure how to make that happen in the chart . One easy way is just hardcoded and value in the template in template/server-configmap.yaml
