### DISCUSSION TITLE
High latency in starting decision task[load test]

### DISCUSSION THREAD

**Discussion by alexfjw** [uber/cadence#4363] [General]
Hi there, any idea what might contribute to high latency in starting a decision task?

We've been running a load test on a single task list, aiming to reach 100 wfs/s.  
The workflow only runs 1 activity, which is to return the variables passed to it. (i.e. minimal processing)

I notice that the number of workflows created can hit 100 wfs/s after enabling scalable tasks lists. However, the activities created are less than the number of workflows triggered & hovers around 60/s. The number of pending workflows eventually increases and times out.

The only error log I get is `RemoteSyncMatchedError{Message: remote sync match failed}` from matching service, which I am unsure how to fix.

Any idea what I might have missed?

![image](https://user-images.githubusercontent.com/11351531/129435670-c8b02cde-31c3-4b36-8205-05594bd120d3.png)

Other info:
- On Mysql for persistence, but did not see any metrics relating to high load on the db. We are using 2048 shards.
- I do not think it is an issue with workflow worker count as some of our workers were momentarily idle during the test. 
- We are using some of the dynamic configs shared by others in the slack channel for performance but did not see much of a difference. 
- We are running this on a 4 replica cluster (4 of matching, history, frontend, workers) and also tried scaling history up to 8 but did not see a difference. Did not see high load on the pods.

Dynamic config used
```
    frontend.persistenceMaxQPS:
      - value: 10000
        constraints: {}
    frontend.rps:
      - value: 6000
        constraints: {}
    frontend.domainrps:
      - value: 6000
        constraints: {}
    matching.persistenceMaxQPS:
      - value: 15000
        constraints: {}
    matching.rps:
      - value: 6000
        constraints: {}
    history.taskProcessRPS:
      - value: 5000
        constraints: {}
    history.persistenceMaxQPS:
      - value: 45000
        constraints: {}
    history.rps:
      - value: 15000
        constraints: {}
    history.cacheMaxSize:
      - value: 1024
        constraints: {}
    history.taskSchedulerWorkerCount:
      - value: 800
        constraints: {}
    history.taskSchedulerShardQueueSize:
      - value: 400
        constraints: {}
    history.timerTaskWorkerCount:
      - value: 20
        constraints: {}
    history.transferTaskWorkerCount:
      - value: 20
        constraints: {}
    history.replicatorTaskWorkerCount:
      - value: 20
        constraints: {}
    matching.numTasklistWritePartitions:
      - value: 10
        constraints: {}
    matching.numTasklistReadPartitions:
      - value: 10
        constraints: {}
```
