### ISSUE TITLE
Feature Request: SQL Support: CockroachDB

### ISSUE THREAD

**Issue by SebastianM** [uber/cadence#1834]
As Cassandra uses a lot of hardware resources and is hard to operate for small deployments/companies and MySQL is hard to run in a fault tolerant mode, I'm submitting this feature request to support [CockroachDB](http://cockroachlabs.com) as another SQL based storage.
IMO it would be a good fit for the Cadence and it should be easy to port the mysql base to a cockroach compatible version. What do you think?

**Comment by dharmjit** [comment]
Hi Team, it will be awesome if cadence support cockroach db.

**Comment by venkat1109** [comment]
As long as cockroachDB supports standard SQL and the schema perf characteristics aren't drastically different from MySQL, the effort involved in adding support for it is about a week. Currently, resources aren't allocated for this, but if any one of you are open to making a contribution, I can provide pointers to the code via #cadence slack channel

**Comment by hazcod** [comment]
See https://github.com/uber/cadence/issues/2536 (and my PR)

**Comment by awoods187** [comment]
PM at Cockroach Labs here. Did you run into any issues? Can we be of any help?

**Comment by hazcod** [comment]
@awoods187 I've opened up https://github.com/temporalio/temporal/issues/287 in temporal, which is kind of a reworked fork (grpc, ...) of cadence that will be backed commercially.

**Comment by hazcod** [comment]
Trying this out myself and opened up https://github.com/cockroachdb/cockroach/issues/47599

**Comment by awoods187** [comment]
Awesome! Excited to see how it goes!

**Comment by AngerM** [comment]
It seems to work in basic testing: 
```
version: '3.2'
services:
  postgres:
    image: cockroachdb/cockroach:v20.1.3
    command: start --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
  statsd:
    image: graphiteapp/graphite-statsd
    ports:
      - "2003:2003"
      - "8125:8125"
      - "8126:8126"
  cadence:
    image: ubercadence/server:master-auto-setup
    ports:
      - "7933:7933"
      - "7934:7934"
      - "7935:7935"
      - "7939:7939"
    environment:
      - "DB=postgres"
      - "DB_PORT=26257"
      - "POSTGRES_USER=root"
      - "POSTGRES_SEEDS=postgres"
      - "STATSD_ENDPOINT=statsd:8125"
      - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml"
    depends_on:
      - postgres
  cadence-web:
    image: ubercadence/web:latest
    environment:
      - "CADENCE_TCHANNEL_PEERS=cadence:7933"
    ports:
      - "8088:8088"
    depends_on:
      - cadence
```
