### ISSUE TITLE
Increase archival level of abstraction

### ISSUE THREAD

**Issue by andrewjdawson2016** [uber/cadence#2082]
**Problem**
When archival was first designed two limiting assumptions were made:

- All archival destinations will be blobstores
- All blobstores support basically the same APIs

Recently we have realized both of these assumptions are false. This task is a parent task for several sub-tasks which aim at undoing those initial assumptions.

**Archiver**
Currently on Cadence cluster startup, a blobstore is initialized. This interface is used for all archival code. This approach is not generic enough. In order to generalize this approach I propose raising the level of abstraction to an Archiver interface and removing the blobstore interface completely.

There will be two Archiver interfaces, one for visibility and one for history.

```
HistoryArchiver interface {
    Archive(context, URI, Request) error
    Get(context, URI, Request) (Response, error)
    Describe(context, Request) (Response, error)
}

VisibilityArchiver interface {
    Archive(context, URI, Request) error
    Query(context, URI, Request) (Response, error)
    Describe(context, Request) (Response, error)
}
```

Cadence will be bootstraped with two maps, one map of visibility archivers and another of history archivers. The keys to these maps will be the technology type used to implement that archiver.

**URIs**
Currently bucket name is the config which controls where records get archived to. However this is not generic enough. The solution to this is to have archival destinations be encoded as a URI. The URI includes three elements:

- The type of destination store
- Connection information to that store
- Location information within that store

Examples of URIs look like the following
```
s3://connection_info/bucket_name
kafka://connection_info/topic_name
hdfs://connection_info/tpath_prefix
```

It is the responsibility of the archiver to know how to decode the URI of its type.

**Cluster Level Config**
I propose the static yaml config should look like the following:

```
archival:
    visibility:
        write_status: {enabled, paused, disabled} // has dynamic config overwrite
        read_enabled: {true, false} // has dynamic config overwrite
        s3:
            // config needed to connect to S3 (timeouts, creds etc…)
        // others
    history:
        write_status: {enabled, paused, disabled} // has dynamic config overwrite
        read_enabled: {true, false} // has dynamic config overwrite
        s3:
            // config needed to connect to S3 (timeouts, creds etc…)
        // others

domain:
    archival:
        visibility: 
            default_uri: // some default URI
            default_status: {true, false}
        history: 
            default_uri: // some default URI
            default_status: {true, false} 
```

On cluster startup the two archiver maps will get populated with all archival store types indicated in config. We will not dynamically create new Archivers while running. If a domain is attempted to be configured to an archiver type which does not exist in the map then its an error.

**Per Domain Config**
Today domain config includes status and bucket name. I purpose updating domain config to _instead_ include the following items: 
**Visibility Status:** Either enabled or disabled. This single config controls both whether writing occurs and whether reading occurs. Customers can freely switch between enabled and disabled.
**Visibility URI:** Location to archive visibility records. This is set when visibility archival is enabled for the first time. Once it’s set it can never be changed. It is either set to the cluster default or to a custom overwrite provided. 
**History Status:** Either enabled or disabled. This single config controls both whether writing occurs and whether reading occurs. Customers can freely switch between enabled and disabled.
**History URI:** Location to archive history records. This is set when history archival is enabled for the first time. Once it’s set it can never be changed. It is either set to the cluster default or to a custom overwrite provided. 

These values will be stored in the database and will have no dynamic config overwrites. 

**Adding New Archivers**
In order to add a new archiver technology the following needs to be done
1. Implement the archiver interface using the desired archiver technology. The implementor is free to archiver how ever they want as long as the API is satisfied.
2. As a part of step 1 archiver needs to define a URI format and know how to decode URIs
3. Add config to static yaml to create desired archiver type on startup
4. Create a domain with URI using the desired technology
