### ISSUE TITLE
After cadence upgrade, hit unknown field 'DisablePointerAddresses' in struct literal of type spew.ConfigState

### ISSUE THREAD

**Issue by xbeta** [uber/cadence#237]
My service tries to upgrade to the latest *preview* of `cadence` and run the following

`make clean; rm -rf vendor; make`

```
[INFO]	Replacing existing vendor dependencies
  GO BUILD (1.8.3 darwin/amd64)    myservice
./vendor/go.uber.org/cadence/mock/mock.go:820: unknown field 'DisablePointerAddresses' in struct literal of type spew.ConfigState
./vendor/go.uber.org/cadence/mock/mock.go:821: unknown field 'DisableCapacities' in struct literal of type spew.ConfigState
make: *** [myservice] Error 2
```

Workaround for now by pinning the version on `glide.yaml`:

```
- package: github.com/davecgh/go-spew
  version: 346938d642f2ec3594ed81d874461961cd0faa76
  subpackages:
  - spew
```

But I believe there should be a longer term fix for this.
