### ISSUE TITLE
Unable to add ConnectAttributes in MySQL DSN url

### ISSUE THREAD

**Issue by SachinHg** [uber/cadence#2968]
While trying to add custom `connectAttributes` to mysql DSN url, the resultant map of key-value pairs is an empty map. 
For e.g., consider the below part of a `development.yaml` file which will be used while starting the cadence server.
```
persistence:
  defaultStore: mysql-default
  visibilityStore: mysql-visibility
  numHistoryShards: 4
  datastores:
    mysql-default:
      sql:
        pluginName: "mysql"
        databaseName: "cadence"
        connectAddr: "127.0.0.1:3306"
        connectProtocol: "tcp"
        user: "cadence"
        password: "cadence"
        maxConns: 20
        maxIdleConns: 20
        maxConnLifetime: "1h"
        connectAttributes:
          tx_isolation: "READ-COMMITTED"
        tls: 
          enabled: true
          config: "skip-verify" 
```
When I try to see the value of `ConnectAttributes` in `config.SQL`, it returns an empty map like below:
`{User:cadence Password:cadence PluginName:mysql DatabaseName:cadence ConnectAddr:127.0.0.1:3306 ConnectProtocol: ConnectAttributes:map[] MaxQPS:0 MaxConns:0 MaxIdleConns:0 MaxConnLifetime:0s NumShards:0 TLS:0xc00037c300}`
After debugging into this, I found out that at https://github.com/uber/cadence/blob/master/tools/sql/handler.go#L82, not all the config values are added. 
Upon adding the `ConnectAttributes`, I was able to see the proper values in `config`.
However, I want to know if this an issue or is this done deliberately.

Thanks.
