### ISSUE TITLE
Cannot run service as NonRoot

### ISSUE THREAD

**Issue by ruccoon** [uber/cadence#3471]
**Describe the bug**
When I try to install the cadence service in k8s and run as NonRoot, i.e
```
    securityContext:
      fsGroup: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
```
The pod shows error 
```
+ dockerize -template /etc/cadence/config/config_template.yaml:/etc/cadence/config/docker.yaml
2020/08/21 22:38:17 unable to create open /etc/cadence/config/docker.yaml: permission denied
```
Cadence server cannot start, as it doesn't has permission to output the template to /etc/cadene/config/ if the server is running as NonRoot user.
https://github.com/uber/cadence/blob/master/docker/start-cadence.sh#L5

**To Reproduce**
Is the issue reproducible? 
- [Yes]

**Steps to reproduce the behavior:**
Run cadence server as NonRoot user. For example, see the describe section above.

**Expected behavior**
Cadence server can run as NonRoot user
