### ISSUE TITLE
Cadence Service is exiting 

### ISSUE THREAD

**Issue by omfd** [uber/cadence#3834]
**Describe the bug**
Cadence service is exiting again and again with the below mentioned error
 `2020/12/08 09:34:38 cassandra schema version compatibility check failed: version mismatch for keyspace/database: "cadence". Expected version: 0.30 cannot be greater than Actual version: 0.25`

**To Reproduce**
Is the issue reproducible? 
- [Yes]

**Steps to reproduce the behavior:**
**docker-compose up and try to register a domain** 

```
version: '3'
services:
  cassandra:
    image: cassandra:3.11
    volumes:
      - cassandra:/var/lib/cassandra
    ports:
      - "9042:9042"
  statsd:
    image: graphiteapp/graphite-statsd
    ports:
      - "8080:80"
      - "2003:2003"
      - "8125:8125"
      - "8126:8126"
  cadence:
    image: ubercadence/server:master-auto-setup
    ports:
     - "7933:7933"
     - "7934:7934"
     - "7935:7935"
     - "7939:7939"
    environment:
      - "CASSANDRA_SEEDS=cassandra"
      - "STATSD_ENDPOINT=statsd:8125"
      - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml"
    depends_on:
      - cassandra
      - statsd
  cadence-web:
    image: ubercadence/web:latest
    environment:
      - "CADENCE_TCHANNEL_PEERS=cadence:7933"
    ports:
      - "8088:8088"
    depends_on:
      - cadence
volumes:
  cassandra:
```

**Expected behavior**
Service should be running ;)

**Screenshots**
[Screenshot](https://imgur.com/a/Do35edQ)
