### ISSUE TITLE
Cadence on top of SQL

### ISSUE THREAD

**Issue by meiliang86** [uber/cadence#854]
Implement SQL persistence so that Cadence can run on top of SQL database.
We should rely on general SQL interface so the actual DB implementation can be swappable.

**Comment by ryanwalls** [comment]
@meiliang86 Any updates on this?  We were hoping to use this in the next couple weeks.

**Comment by meiliang86** [comment]
Yes. We recently implemented all the SQL persistence (other than visibility) and made it working on top of MySQL (we use general SQL library so it should work with other SQL implementations). @uber-qlam can you send out instructions so people can try?

**Comment by uber-qlam** [comment]
Hi, let me know if these instructions work for you.

1. Stand up a MySQL instance at `localhost:3306`.
1. Create a schema called `catalyst_test` and give a user `uber` with password `uber` privileges to it.
1. Create a file `/tmp/usemysql`. (This "hack" is the current way of enabling/disabling SQL persistence.)
1. If you already have a local cassandra instance with the cadence-visibility keyspace, you can skip this.
* Go to the `cadence` source and run `make install-schema`.
1. Clone `*uber-qlam*/cadence` into `$GOPATH/src/github.com/uber/cadence`. You might need to displace your copy of `uber/cadence`.
1. Check out revision `helloworld2`.
1. Build with `make bins`.
1.  Install the MySQL schema.
```
migrate -source file://./common/persistence/sql/schema -database mysql://uber:uber@tcp(localhost:3306)/catalyst_test up
```
1. Start cadence: `cadence-server start`

**Comment by sagikazarmark** [comment]
Hey, this is awesome! Looking forward to it.

Is this feature actively worked on or is it still a proposal + a POC implementation? Is there a decision that SQL is going to be supported in Cadence?

Is there a way we (users) can help with this feature other than testing it?

**Comment by sagikazarmark** [comment]
That's good to hear! Is there a rough ETA when that will happen? Cassandra is a no-go for us in the long term and we are about to make a decision about using Cadence in our project.

**Comment by mfateev** [comment]
I'm currently working on merging the SQL support into the master branch. I target this or next week to land it. It is still missing the visibility functions support. So realistically it would take another week or two to get all of the API implemented. Then we need thorough performance testing to consider it officially ready. 

So less than in a month you could start your performance tests to speed things up.

Here is the branch I'm currently using for development: https://github.com/mfateev/cadence/tree/sqlpersistence

**Comment by h7kanna** [comment]
Are the instructions to run with Mysql still valid on master branch?

**Comment by mfateev** [comment]
No, the instructions are not valid for it.
The SQL persistence unit tests can be executed through "make" assuming that a mysql database with user "uber" and password "uber" is reachable on a localhost. Most of them are still disabled as they are not passing and I'm working on fixing them.
We are also working on refactoring configuration and initialization code to support pluggable persistence implementations. After this code is merged the updated instructions will be posted.

**Comment by h7kanna** [comment]
Hi @mfateev , I see good progress on SQL implementation,
Can you update the instructions to run locally with SQL setup, I want to try it out and if possible contribute to it further. 
Thanks,

**Comment by sagikazarmark** [comment]
Any update? no change on that branch since a month ago.

**Comment by venkat1109** [comment]
All of the pieces needed to execute a fully functional cadence server on top of SQL are now in master. Cadence config now supports multiple data store options (SQL & Cassandra):

https://github.com/uber/cadence/blob/master/config/development.yaml#L5
https://github.com/uber/cadence/blob/master/common/service/config/config.go#L114

The persistence layer unit tests also run against both SQL/Cassandra as of today. That said, we are still in the process of testing for correctness / performance / scalability. We expect to find bugs and/or perf issues as we are doing this. Meanwhile, if you like to try out running cadence on top of SQL, you can follow the steps below:

Install Schema
https://github.com/uber/cadence/tree/master/schema/mysql/

Modify Server Config
https://github.com/uber/cadence/blob/master/config/development.yaml#L1
```
persistence:
  defaultStore: mysql-default
  visibilityStore: cass-visibility -- mysql has support for visibility, but this is untested
  numHistoryShards: 4
  datastores:
    mysql-default:
     sql:
        driverName: "mysql"
        user: "userName"
        password: "password"
        connectAddr: "addr:port"
        connectProtocol: "tcp"
        databaseName: "yourCadenceDBName"
    cass-visibility:
      cassandra:
        hosts: "127.0.0.1"
        keyspace: "cadence_visibility"
        consistency: "One"
```
